version: "2"

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"

python:
  install:
    - requirements: docs/api_docs/python/requirements.txt

sphinx:
  configuration: docs/api_docs/python/conf.py
